FROM eclipse-temurin:21-jdk

WORKDIR /app

RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

COPY build/libs/*.jar app.jar

ENTRYPOINT ["java","-jar","app.jar"]
