services:

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - streaming-network


  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - streaming-network

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: native
    networks:
      - streaming-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10


  discovery:
    build:
      context: ./discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - streaming-network
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8222:8222"
    networks:
      - streaming-network
    depends_on:
      discovery:
        condition: service_healthy
      config-server:
        condition: service_healthy

  auth:
    build:
      context: ./spring_boot_auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "8070:8070"
    networks:
      - streaming-network
    depends_on:
      postgres:
        condition: service_started
      config-server:
        condition: service_healthy
      discovery:
        condition: service_healthy

  catalog:
    build:
      context: ./catalog
      dockerfile: Dockerfile
    container_name: catalog
    ports:
      - "8090:8090"
    networks:
      - streaming-network
    depends_on:
      mongodb:
        condition: service_started
      postgres:
        condition: service_started
      config-server:
        condition: service_healthy
      discovery:
        condition: service_healthy

  favourites:
    build:
      context: ./favourites
      dockerfile: Dockerfile
    container_name: favourites
    ports:
      - "8050:8050"
    networks:
      - streaming-network
    depends_on:
      postgres:
        condition: service_started
      config-server:
        condition: service_healthy
      discovery:
        condition: service_healthy

  playback:
    build:
      context: ./playback
      dockerfile: Dockerfile
    container_name: playback
    ports:
      - "8080:8080"
    networks:
      - streaming-network
    depends_on:
      mongodb:
        condition: service_started
      postgres:
        condition: service_started
      config-server:
        condition: service_healthy
      discovery:
        condition: service_healthy


volumes:
  postgres-data:
  mongo-data:


networks:
  streaming-network:
    driver: bridge