version: '3.8'

services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

#  redis:
#    image: redis:7
#    container_name: redis
#    ports:
#      - "6379:6379"