eureka:
  instance:
    instance-id: ${INSTANCE_ID:${random.uuid}}
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka/

server:
  port: 8080

spring:
  application:
    name: playback

  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

  data:
    mongodb:
      uri: mongodb://mongodb:27017/playback_db
      database: playback_db

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

streaming:
  node:
    id: ${INSTANCE_ID:playback-local}
    host: ${INSTANCE_HOST:localhost}
    port: ${INSTANCE_PORT:8080}
    capacity: ${STREAMING_CAPACITY:100}